version: '3'
services:

  jms:
    container_name: jms
    image: vromero/activemq-artemis
    restart: always
    environment:
      ARTEMIS_USERNAME: 'lucasbrunkhorst'
      ARTEMIS_PASSWORD: 'root'
    ports:
      - 61616:61616
      - 8161:8161
    expose:
      - 61616
      - 8161

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    expose:
      - 9090
    ports:
      - 9090:9090

  grafana:
      image: grafana/grafana:latest
      container_name: monitoring_grafana
      restart: unless-stopped
      links:
        - prometheus:prometheus
      expose:
        - 3000
      ports:
        - 3000:3000
  trace:
    container_name: trace
    image: openzipkin/zipkin
    restart: always
    ports:
      - 9411:9411
    expose:
      - 9411
  logspout:
    image: gliderlabs/logspout:v3
    command: 'udp://logstash:5000'
    links:
      - logstash
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    depends_on:
      - elasticsearch
      - logstash
      - kibana

  logstash:
      image: logstash:2.1.1
      environment:
        - STDOUT=true
      links:
        - elasticsearch
      depends_on:
        - elasticsearch
        - kibana
      command: 'logstash -e "input { udp { port => 5000 } } output { elasticsearch { hosts => elasticsearch } }"'

  kibana:
      image: kibana:4.1.2
      links:
        - elasticsearch
      environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch

  elasticsearch:
      image: elasticsearch:1.5.2
      ports:
        - 9200:9200
        - 9300:9300